# -*- coding: utf-8 -*-
"""COP1000_Module04_GuessTheNumber.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1COtbtGs911Fg7pDmaXvHTLVFAJ7YeLTB
"""

import random

secret_number = random.randint(1, 20)
attempts = 0

print("Guess a number from 1 to 20 or die.")

while True:
    try:
        guess = int(input("What's the number?: "))
        attempts += 1

        if guess < secret_number:
            print("That's too low, dummy!")
        elif guess > secret_number:
            print("Too high, try again.")
        else:
            print(f"You guessed the number in {attempts} attempts. You're safe for now.")
            break
    except ValueError:
        print("How about a whole number this time?")

    if attempts >= 10:
        print("You're dead to me.")
        break