# -*- coding: utf-8 -*-
"""COP1000_Module01_HelloPython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16hYrlEYTgmYsygepkPVE-TYtYwFOSSst
"""

#short introduction
print("My name is Zach Krantz, I am a student at Saint John's River State College. I am studying Network Systems Tech.")
#academic or career interest
print("I am interested in cyber security and devops as a potential career path.")
#displays something I want to learn in python
print("Something I want to learn in python is how to script for pentesting or creating GUI for my linux projects at home.")
#displays closing message
print("I am excited to enhance my proficency at coding in python!")

